<?php 

namespace Drupal\imagehash;


function image_hash($uri, $bits = 8, $method=NULL) {
	
	if(!$method) {
		$method = ImageHash::$default_method;
	}
	
	switch ($method) {
		case 'phash':
			return ImageHash::phash($uri, $bits);
		break;
		
		case 'bhash':
			return ImageHash::bhash($uri, $bits);
		break;
		
		case 'whash':
			return ImageHash::whash($uri, $bits);
		break;
			
		default:
			die("Method $method not supported");
			//return call_user_func([ImageHash, ], $uri, $bits);
		break;
	}
}



function db_number($method) {
	
	$db_numbers = [
		'phash' => 1,
		'dhash' => 2,
		'whash' => 3,
		'bhash' => 4
	];
	
	if(array_key_exists($method, $db_numbers)) {
		return $db_numbers[$method];
	}
	else {
		return 0;
	}
}