
-- --------------------------------------------------------

--
-- Table structure for table `cachetags`
--

CREATE TABLE `cachetags` (
  `tag` varchar(255) CHARACTER SET ascii NOT NULL DEFAULT '' COMMENT 'Namespace-prefixed tag string.',
  `invalidations` int(11) NOT NULL DEFAULT '0' COMMENT 'Number incremented when the tag is invalidated.'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Cache table for tracking cache tag invalidations.';

--
-- Dumping data for table `cachetags`
--

INSERT INTO `cachetags` (`tag`, `invalidations`) VALUES
('4xx-response', 48),
('block_content_view', 1),
('breakpoints', 39),
('comment_view', 1),
('config:action_list', 4),
('config:block.block.bartik_account_menu', 1),
('config:block.block.bartik_branding', 1),
('config:block.block.bartik_breadcrumbs', 1),
('config:block.block.bartik_content', 1),
('config:block.block.bartik_footer', 1),
('config:block.block.bartik_help', 1),
('config:block.block.bartik_local_actions', 1),
('config:block.block.bartik_local_tasks', 1),
('config:block.block.bartik_main_menu', 1),
('config:block.block.bartik_messages', 1),
('config:block.block.bartik_page_title', 1),
('config:block.block.bartik_powered', 1),
('config:block.block.bartik_search', 1),
('config:block.block.bartik_tools', 1),
('config:block.block.drupal8_zymphonies_theme_account_menu', 1),
('config:block.block.drupal8_zymphonies_theme_branding', 1),
('config:block.block.drupal8_zymphonies_theme_breadcrumbs', 1),
('config:block.block.drupal8_zymphonies_theme_content', 1),
('config:block.block.drupal8_zymphonies_theme_footer', 1),
('config:block.block.drupal8_zymphonies_theme_help', 1),
('config:block.block.drupal8_zymphonies_theme_local_actions', 1),
('config:block.block.drupal8_zymphonies_theme_local_tasks', 1),
('config:block.block.drupal8_zymphonies_theme_main_menu', 1),
('config:block.block.drupal8_zymphonies_theme_messages', 1),
('config:block.block.drupal8_zymphonies_theme_page_title', 1),
('config:block.block.drupal8_zymphonies_theme_powered', 1),
('config:block.block.drupal8_zymphonies_theme_search', 1),
('config:block.block.seven_breadcrumbs', 1),
('config:block.block.seven_content', 1),
('config:block.block.seven_help', 1),
('config:block.block.seven_local_actions', 1),
('config:block.block.seven_login', 1),
('config:block.block.seven_messages', 1),
('config:block.block.seven_page_title', 1),
('config:block.block.seven_primary_local_tasks', 1),
('config:block.block.seven_secondary_local_tasks', 1),
('config:block_content_type_list', 1),
('config:block_list', 2),
('config:comment_type_list', 1),
('config:contact.form.feedback', 1),
('config:contact_form_list', 3),
('config:core.extension', 52),
('config:core.menu.static_menu_link_overrides', 1),
('config:drupal8_zymphonies_theme.settings', 1),
('config:editor_list', 1),
('config:entity_form_display_list', 1),
('config:entity_form_mode_list', 1),
('config:entity_view_display_list', 1),
('config:entity_view_mode_list', 5),
('config:filter_format_list', 2),
('config:image_style_list', 1),
('config:menu_list', 2),
('config:node.settings', 1),
('config:node_type_list', 1),
('config:rdf_mapping_list', 1),
('config:search_page_list', 1),
('config:shortcut.set.default', 1),
('config:shortcut_set_list', 2),
('config:system.date', 1),
('config:system.file', 1),
('config:system.menu.account', 47),
('config:system.menu.admin', 48),
('config:system.menu.devel', 6),
('config:system.menu.footer', 31),
('config:system.menu.main', 46),
('config:system.menu.tools', 44),
('config:system.site', 3),
('config:system.theme', 1),
('config:taxonomy_vocabulary_list', 1),
('config:tour_list', 1),
('config:user.role.anonymous', 2),
('config:user.role.authenticated', 2),
('config:user.settings', 1),
('config:user_role_list', 3),
('config:views.view.archive', 1),
('config:views.view.block_content', 1),
('config:views.view.comments_recent', 1),
('config:views.view.content', 1),
('config:views.view.content_recent', 1),
('config:views.view.files', 1),
('config:views.view.frontpage', 1),
('config:views.view.glossary', 1),
('config:views.view.taxonomy_term', 1),
('config:views.view.user_admin_people', 1),
('config:views.view.who_s_new', 1),
('config:views.view.who_s_online', 1),
('config:view_list', 1),
('contact_message_view', 1),
('contextual_links_plugins', 48),
('element_info_build', 48),
('entity_bundles', 72),
('entity_field_info', 86),
('entity_types', 82),
('file_list', 3),
('local_action', 48),
('local_task', 50),
('node_view', 1),
('rendered', 5),
('routes', 48),
('route_match', 49),
('taxonomy_term_view', 1),
('theme_registry', 50),
('user:1', 2),
('user_list', 3),
('user_view', 1),
('views_data', 1);
