<?php


namespace Drupal\UserInterface;

use \Drupal\Core\Database\StatementInterface;
use Drupal\user\UserInterface;
use Drupal\dcfs\DCFSearch;

define('IMAGES_TABLE', 'iut_images');


/**
 * 
 * @param string | array $id
 */
function load_image($id) {
	$query = db_select(IMAGES_TABLE, 'm')
		->fields('m');
	
	if(is_string($id)) {
		$query->condition('image_id', $id);
	}
	elseif (is_array($id)) {
		$query->condition('image_id', $id,  'IN');
	}
	$image = $query->execute()
		->fetchAll();
	
	return $image;
}


function load_image_by_hash($hash) {
	$image = db_select(IMAGES_TABLE, 'm')
	->fields('m')
	->condition('hash', $hash)
	->execute()
	->fetchAll();

	return $image;
}


function insert_image($uri, $hash) {
	$inserted = db_insert(IMAGES_TABLE)
		->fields([
			'uri' => $uri,
			'hash' => $hash
		])
		->execute();
		
	return $inserted;
}



function hex2bin($number) {
	
	$slices = str_split($number, 1);
	$output = '';
	foreach ($slices as $num) {
		$output .= str_pad(base_convert($num, 16, 2), 4, '0', STR_PAD_LEFT);
	}
	return $output;
}



function run_test($num = 20, $radii = [7]) {
	$images = db_select(IMAGES_TABLE, 'm')
		->fields('m')
		->range(0, $num)
		->orderRandom()
		->execute()
		->fetchAll();

	if(!$images) {
		return "no image selected for test";
	}
	$count = count($images);
	$output = [];
	
	$dcfs = new DCFSearch();
	foreach ($radii as $r) {
		$sum_total_time = 0;
		$sum_inter_time = 0;
		foreach ($images as $key => $image) {
			$query = hex2bin($image->hash);
			$result = $dcfs->search2($query, $r);
			$sum_total_time += $result['info']['total_time'];
			$sum_inter_time += $result['info']['intersect_time'];
			
		}
		$output[$r] = [
			'total_time' => $sum_total_time / $count,
			'intersect_time' => $sum_inter_time / $count
		];
	}
	return $output;
}